### ISSUE TITLE
The current state of the module

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/content-module#4]
@pi0 @Atinux 

Hey sorry for the delay haven't had much time this week. Here's an update on where I'm at right now.

The minimal requirement is down: you can create components based on markdown files and structure the conent based on a layout with template and styles and the front-matter data.

But there are three problems I haven't been able to fix:

- Unfortunately, Webpack limits how you can [require assets](https://webpack.js.org/guides/dependency-management/), as the dependencies must be in the `require('./content/someDir' + dynamicName + '.md'`) format, which limits the extent to which this module can abstract the fecthing of content.
- Asyncdata is resolved before templates are compiled. So you can't include the compiled components via the app context without the stand alone build. And you can't access the compiled components in the client, e.g.  via vue mixin, because the content retrieved via Node API is not available. 
- The content components work with `nuxt build`, but `nuxt generate`  throws an unexpected token error which causes the process to fail. The documentation specify how to add dynamic routes, but not how to dynamically add nested routes, which might be the problem.

As @pi0 said from the beginning, doing it via server middleware and axios seems more feasible. 

@znck Seems to have a working prototype of [nuxt-blog-module](https://github.com/znck/nuxt-module-blog/tree/master/). And if that is the case there is not use in repeating the work. Though it would be better l to have a more general solution that works for more than just blogs. 

Let me know what you guys think and any input you may have on how to best procceed!

**Comment by znck** [comment]
@alidcastano In blog-module, I am more inclined to generate collection & tag pages, support for pagination etc. I'm not spending much time in transpiling markdown to vue component. I presume blog-module can depend on content-module.

**Comment by alidcastano** [comment]
Given the constraints with webpack imports and nuxt server-client integration, I've simplified the module to providing a lightweight abstraction for using the data inside content files inside Nuxt pages. In the future, if there's demand, I'll explore transpiling  markdown to vue components, but right now the integration proved to much of a headache for such rare usage.
